-- Layer 1: Identity
-- Customers sign in with their mobile number and a one-time SMS code, so there
-- are no passwords. A user row is created on the first successful code check.

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile     VARCHAR(11)  NOT NULL,            -- 09xxxxxxxxx
    email      VARCHAR(255),
    first_name VARCHAR(100),                     -- filled in after the first login
    last_name  VARCHAR(100),
    role       VARCHAR(20)  NOT NULL DEFAULT 'CUSTOMER',
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_users_mobile      UNIQUE (mobile),
    CONSTRAINT uk_users_email       UNIQUE (email),
    CONSTRAINT ck_users_mobile      CHECK (mobile ~ '^09[0-9]{9}$'),
    CONSTRAINT ck_users_email_lower CHECK (email = lower(email)),
    CONSTRAINT ck_users_role        CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

-- One-time login codes. Not linked to users: the number may not have an account yet.
-- Only a SHA-256 hash of the code is stored.
CREATE TABLE otp_codes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile      VARCHAR(11) NOT NULL,
    code_hash   VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    attempts    INTEGER     NOT NULL DEFAULT 0,  -- wrong guesses so far
    consumed_at TIMESTAMPTZ,                     -- set once the code is used
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_otp_mobile   CHECK (mobile ~ '^09[0-9]{9}$'),
    CONSTRAINT ck_otp_attempts CHECK (attempts >= 0)
);

-- Latest code per number, and rate limiting ("max N codes per 10 minutes").
CREATE INDEX idx_otp_mobile_created ON otp_codes (mobile, created_at DESC);

-- Reference data: Iran's 31 provinces.
CREATE TABLE provinces (
    id   SMALLINT    PRIMARY KEY,
    name VARCHAR(50) NOT NULL,

    CONSTRAINT uk_provinces_name UNIQUE (name)
);

INSERT INTO provinces (id, name) VALUES
    (1,  'آذربایجان شرقی'),
    (2,  'آذربایجان غربی'),
    (3,  'اردبیل'),
    (4,  'اصفهان'),
    (5,  'البرز'),
    (6,  'ایلام'),
    (7,  'بوشهر'),
    (8,  'تهران'),
    (9,  'چهارمحال و بختیاری'),
    (10, 'خراسان جنوبی'),
    (11, 'خراسان رضوی'),
    (12, 'خراسان شمالی'),
    (13, 'خوزستان'),
    (14, 'زنجان'),
    (15, 'سمنان'),
    (16, 'سیستان و بلوچستان'),
    (17, 'فارس'),
    (18, 'قزوین'),
    (19, 'قم'),
    (20, 'کردستان'),
    (21, 'کرمان'),
    (22, 'کرمانشاه'),
    (23, 'کهگیلویه و بویراحمد'),
    (24, 'گلستان'),
    (25, 'گیلان'),
    (26, 'لرستان'),
    (27, 'مازندران'),
    (28, 'مرکزی'),
    (29, 'هرمزگان'),
    (30, 'همدان'),
    (31, 'یزد');

CREATE TABLE addresses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    recipient_name   VARCHAR(200) NOT NULL,
    recipient_mobile VARCHAR(11)  NOT NULL,
    province_id      SMALLINT     NOT NULL,
    city             VARCHAR(100) NOT NULL,
    address_line     TEXT         NOT NULL,       -- street, alley, building (نشانی پستی)
    plaque           VARCHAR(20)  NOT NULL,       -- پلاک
    unit             VARCHAR(20),                 -- واحد
    postal_code      VARCHAR(10)  NOT NULL,
    is_default       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_addresses_user        FOREIGN KEY (user_id)     REFERENCES users (id)     ON DELETE CASCADE,
    CONSTRAINT fk_addresses_province    FOREIGN KEY (province_id) REFERENCES provinces (id) ON DELETE RESTRICT,
    CONSTRAINT ck_addresses_mobile      CHECK (recipient_mobile ~ '^09[0-9]{9}$'),
    CONSTRAINT ck_addresses_postal_code CHECK (postal_code ~ '^[0-9]{10}$')
);

CREATE INDEX idx_addresses_user ON addresses (user_id);

-- At most one default address per user, enforced by the database.
CREATE UNIQUE INDEX uk_addresses_one_default ON addresses (user_id) WHERE is_default;
