-- Layer 2: Catalog
-- A product is the shared description; a variant is the sellable unit with its
-- own SKU, price and stock. Every product has at least one variant (products
-- without options get one variant with attributes '{}').
-- All prices are whole Rials (BIGINT). The UI shows Toman (Rial / 10).

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,
    name        VARCHAR(100) NOT NULL,           -- Persian display name
    slug        VARCHAR(120) NOT NULL,           -- Latin, used in URLs
    image_url   VARCHAR(500),                    -- icon for the home page category row
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_categories_slug     UNIQUE (slug),
    CONSTRAINT fk_categories_parent   FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT ck_categories_not_self CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE INDEX idx_categories_parent ON categories (parent_id);

CREATE TABLE brands (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,            -- Persian name
    name_en    VARCHAR(100),                     -- Latin name
    slug       VARCHAR(120) NOT NULL,
    logo_url   VARCHAR(500),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_brands_slug UNIQUE (slug)
);

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT       NOT NULL,
    brand_id    BIGINT,
    name        VARCHAR(250) NOT NULL,           -- Persian title
    name_en     VARCHAR(250),                    -- Latin subtitle shown under the title
    slug        VARCHAR(250) NOT NULL,
    description TEXT,                            -- معرفی
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_products_slug     UNIQUE (slug),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_products_brand    FOREIGN KEY (brand_id)    REFERENCES brands (id)     ON DELETE SET NULL
);

CREATE INDEX idx_products_category       ON products (category_id);
CREATE INDEX idx_products_brand          ON products (brand_id);
CREATE INDEX idx_products_active_created ON products (active, created_at DESC);

-- The مشخصات table on the product page: grouped name/value rows.
CREATE TABLE product_specs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL,
    group_name VARCHAR(100),                     -- e.g. مشخصات کلی
    name       VARCHAR(100) NOT NULL,            -- e.g. وزن
    value      VARCHAR(500) NOT NULL,            -- e.g. ۲۵۰ گرم
    sort_order INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT fk_specs_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE INDEX idx_specs_product_sort ON product_specs (product_id, sort_order);

CREATE TABLE product_variants (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       BIGINT      NOT NULL,
    sku              VARCHAR(64) NOT NULL,
    attributes       JSONB       NOT NULL DEFAULT '{}'::jsonb,  -- e.g. {"color": "مشکی", "size": "M"}
    price            BIGINT      NOT NULL,         -- selling price, Rial
    compare_at_price BIGINT,                       -- crossed-out price; NULL = no discount
    discount_ends_at TIMESTAMPTZ,                  -- set = "amazing offer" with a countdown
    stock_quantity   INTEGER     NOT NULL DEFAULT 0,
    active           BOOLEAN     NOT NULL DEFAULT TRUE,
    version          BIGINT      NOT NULL DEFAULT 0,  -- JPA @Version, prevents overselling
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uk_variants_sku                UNIQUE (sku),
    CONSTRAINT uk_variants_product_attributes UNIQUE (product_id, attributes),
    CONSTRAINT fk_variants_product            FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT ck_variants_attributes_object  CHECK (jsonb_typeof(attributes) = 'object'),
    CONSTRAINT ck_variants_price              CHECK (price >= 0),
    CONSTRAINT ck_variants_compare_at         CHECK (compare_at_price IS NULL OR compare_at_price > price),
    CONSTRAINT ck_variants_offer_needs_discount CHECK (discount_ends_at IS NULL OR compare_at_price IS NOT NULL),
    CONSTRAINT ck_variants_stock              CHECK (stock_quantity >= 0)
);

CREATE INDEX idx_variants_product ON product_variants (product_id);
CREATE INDEX idx_variants_offers  ON product_variants (discount_ends_at) WHERE discount_ends_at IS NOT NULL;

CREATE TABLE product_images (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL,
    variant_id BIGINT,                          -- optional: an image for one variant (e.g. a colour)
    url        VARCHAR(500) NOT NULL,
    alt_text   VARCHAR(255),
    sort_order INTEGER      NOT NULL DEFAULT 0,  -- 0 = main image
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_images_product FOREIGN KEY (product_id) REFERENCES products (id)         ON DELETE CASCADE,
    CONSTRAINT fk_images_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE SET NULL
);

CREATE INDEX idx_images_product_sort ON product_images (product_id, sort_order);
CREATE INDEX idx_images_variant      ON product_images (variant_id);
