-- Layer 3: Shopping cart
-- One persistent cart per user. Items point at live variants and store no
-- price, so the cart always shows current prices.

CREATE TABLE carts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uk_carts_user UNIQUE (user_id),
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT      NOT NULL,
    variant_id BIGINT      NOT NULL,
    quantity   INTEGER     NOT NULL,
    added_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Adding the same variant again increases quantity instead of adding a row.
    CONSTRAINT uk_cart_items_cart_variant UNIQUE (cart_id, variant_id),
    CONSTRAINT fk_cart_items_cart         FOREIGN KEY (cart_id)    REFERENCES carts (id)            ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_variant      FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE,
    CONSTRAINT ck_cart_items_quantity     CHECK (quantity > 0)
);

CREATE INDEX idx_cart_items_variant ON cart_items (variant_id);
