-- Layer 4: Orders and payments
-- A frozen record of each purchase. Prices, names, variant attributes and the
-- shipping address are copied at checkout, so later edits never change history.
-- All amounts are whole Rials. Named "orders" because ORDER is a reserved word.

CREATE TABLE orders (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT       NOT NULL,
    order_number          VARCHAR(20)  NOT NULL,   -- shown to customers
    status                VARCHAR(20)  NOT NULL DEFAULT 'PENDING_PAYMENT',
    items_total           BIGINT       NOT NULL,   -- sum of line totals
    discount_total        BIGINT       NOT NULL DEFAULT 0,  -- savings vs. crossed-out prices, for display
    shipping_fee          BIGINT       NOT NULL DEFAULT 0,
    total                 BIGINT       NOT NULL,   -- amount to pay

    -- Shipping address snapshot (mapped as a JPA @Embeddable)
    ship_recipient_name   VARCHAR(200) NOT NULL,
    ship_recipient_mobile VARCHAR(11)  NOT NULL,
    ship_province         VARCHAR(50)  NOT NULL,   -- province name, copied as text
    ship_city             VARCHAR(100) NOT NULL,
    ship_address_line     TEXT         NOT NULL,
    ship_plaque           VARCHAR(20)  NOT NULL,
    ship_unit             VARCHAR(20),
    ship_postal_code      VARCHAR(10)  NOT NULL,

    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_orders_number  UNIQUE (order_number),
    CONSTRAINT fk_orders_user    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_orders_status  CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED')),
    CONSTRAINT ck_orders_amounts CHECK (items_total >= 0 AND discount_total >= 0 AND shipping_fee >= 0),
    CONSTRAINT ck_orders_total   CHECK (total = items_total + shipping_fee)
);

CREATE INDEX idx_orders_user_created ON orders (user_id, created_at DESC);
CREATE INDEX idx_orders_status       ON orders (status);

CREATE TABLE order_items (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           BIGINT       NOT NULL,
    variant_id         BIGINT       NOT NULL,
    product_name       VARCHAR(250) NOT NULL,          -- snapshot
    sku                VARCHAR(64)  NOT NULL,          -- snapshot
    variant_attributes JSONB        NOT NULL DEFAULT '{}'::jsonb,  -- snapshot
    unit_price         BIGINT       NOT NULL,          -- price actually charged
    original_price     BIGINT,                         -- crossed-out price at the time, if any
    quantity           INTEGER      NOT NULL,
    line_total         BIGINT       NOT NULL,

    CONSTRAINT fk_order_items_order      FOREIGN KEY (order_id)   REFERENCES orders (id)           ON DELETE CASCADE,
    CONSTRAINT fk_order_items_variant    FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE RESTRICT,
    CONSTRAINT ck_order_items_quantity   CHECK (quantity > 0),
    CONSTRAINT ck_order_items_price      CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_original   CHECK (original_price IS NULL OR original_price > unit_price),
    CONSTRAINT ck_order_items_line_total CHECK (line_total = unit_price * quantity)
);

CREATE INDEX idx_order_items_order   ON order_items (order_id);
CREATE INDEX idx_order_items_variant ON order_items (variant_id);

-- One row per payment attempt. Zarinpal flow: request -> authority, redirect the
-- customer, then verify -> ref_id. A failed attempt followed by a retry = two rows.
CREATE TABLE payments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT       NOT NULL,
    gateway        VARCHAR(20)  NOT NULL,   -- ZARINPAL or MOCK
    authority      VARCHAR(100),            -- gateway token issued before redirect
    ref_id         VARCHAR(100),            -- gateway reference after successful verify (کد پیگیری)
    card_pan       VARCHAR(20),             -- masked card number returned by the gateway
    amount         BIGINT       NOT NULL,   -- Rial
    status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    failure_reason VARCHAR(255),
    paid_at        TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_payments_order     FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT,
    CONSTRAINT uk_payments_authority UNIQUE (authority),
    CONSTRAINT uk_payments_ref_id    UNIQUE (ref_id),
    CONSTRAINT ck_payments_gateway   CHECK (gateway IN ('ZARINPAL', 'MOCK')),
    CONSTRAINT ck_payments_status    CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED')),
    CONSTRAINT ck_payments_amount    CHECK (amount > 0)
);

CREATE INDEX idx_payments_order ON payments (order_id);
