-- Layer 5: Engagement
-- Reviews (دیدگاه) are per product, one per user per product, and are shown
-- only after an admin approves them.

CREATE TABLE reviews (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    product_id        BIGINT       NOT NULL,
    rating            INTEGER      NOT NULL,
    title             VARCHAR(150),
    comment           TEXT,
    recommended       BOOLEAN,                    -- "پیشنهاد می‌کنم" / "پیشنهاد نمی‌کنم"; NULL = no opinion
    verified_purchase BOOLEAN      NOT NULL DEFAULT FALSE,
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_reviews_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_reviews_user         FOREIGN KEY (user_id)    REFERENCES users (id)    ON DELETE CASCADE,
    CONSTRAINT fk_reviews_product      FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT ck_reviews_rating       CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_reviews_status       CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- Approved reviews of a product, newest first.
CREATE INDEX idx_reviews_product_status ON reviews (product_id, status, created_at DESC);
