-- Layer 1 extension: refresh tokens for JWT sign-in
-- Access tokens are short-lived JWTs and are never stored. Refresh tokens are random
-- strings; only their SHA-256 hash is kept. Each refresh rotates the token: the old
-- row is revoked and a new one is issued. Presenting a revoked token again means it
-- was stolen, so all of that user's tokens are revoked.

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,                    -- set on rotation, logout or reuse detection
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
